"""
rl/train.py — Main PPO training script

Usage:
  python rl/train.py --episodes 1000 --curriculum-start 1

Architecture:
  Browser simulator ←WebSocket→ Python trainer
  
  Browser handles:  physics, perception, rendering
  Python handles:   neural network training, logging
"""

import argparse
import asyncio
import json
import os
import time
from pathlib import Path

import numpy as np

from ppo import PPOTrainer
from ws_bridge import SimulatorBridge


def write_summary_report(log_dir, episode, episode_rewards, collision_count, curriculum_stage, best_avg_reward):
    """Write human-readable TRAINING_SUMMARY.md and visual dashboard.html."""
    n = len(episode_rewards)
    if n == 0:
        return

    recent_10 = episode_rewards[-10:]
    avg_10 = sum(recent_10) / len(recent_10)
    col_rate = (collision_count / episode) * 100

    # Trend calculation
    chunk = min(50, n // 2) if n >= 20 else max(1, n // 2)
    early_r = sum(episode_rewards[:chunk]) / chunk
    recent_r = sum(episode_rewards[-chunk:]) / chunk
    diff = recent_r - early_r
    trend = "IMPROVING (+{:.1f} pts)".format(diff) if diff > 5 else "PROGRESSING" if diff > 0 else "EXPLORING"

    md_path = Path(log_dir) / 'TRAINING_SUMMARY.md'
    with open(md_path, 'w', encoding='utf-8') as f:
        f.write("# 🚗 V2V Autonomous Driving — RL Learning Progress\n\n")
        f.write(f"> **Last Updated**: Episode {episode} | **Curriculum**: Stage {curriculum_stage}\n\n")
        f.write("## 📊 Executive Summary\n\n")
        f.write(f"| Metric | Current Value | Target / Status |\n")
        f.write(f"| :--- | :--- | :--- |\n")
        f.write(f"| **Learning Status** | **{trend}** | Improving Policy |\n")
        f.write(f"| **Total Episodes** | `{episode}` | Ongoing |\n")
        f.write(f"| **Curriculum Stage** | `Stage {curriculum_stage}` | Stage 1 (Empty) → Stage 7 (Mixed) |\n")
        f.write(f"| **Latest 10-Ep Avg Reward** | `{avg_10:.1f}` | Higher is better (> +50) |\n")
        f.write(f"| **Best Rolling 100 Reward** | `{best_avg_reward:.1f}` | Peak performance |\n")
        f.write(f"| **Overall Collision Rate** | `{col_rate:.1f}%` ({collision_count}/{episode}) | Target < 15% |\n\n")
        f.write("## 📈 Learning Trend Diagnosis\n\n")
        if n >= 20:
            f.write(f"- **Early vs. Recent Reward**: `{early_r:.1f}` (Early) ➔ **`{recent_r:.1f}`** (Recent)\n")
            if diff > 0:
                f.write(f"- ✅ **Confirmed Learning**: The neural network is making positive policy progress (+{diff:.1f} pts)!\n")
            else:
                f.write(f"- 🔄 **Policy Tuning**: The agent is exploring action boundaries.\n")
        else:
            f.write("- *Agent in early initial exploration phase. Trends emerge after ~30 episodes.*\n")
        f.write("\n---\n*Auto-generated by `rl/train.py`. Re-opens with live updates in IDE.*\n")

    # Generate visual dashboard.html with Chart.js
    html_path = Path(log_dir) / 'dashboard.html'
    ep_labels = [i + 1 for i in range(0, n, max(1, n // 100))]
    sampled_rewards = [round(float(episode_rewards[i - 1]), 1) for i in ep_labels]

    with open(html_path, 'w', encoding='utf-8') as f:
        f.write(f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="refresh" content="10">
  <title>V2V RL Training Dashboard</title>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, monospace; background: #080d1a; color: #e2e8f0; padding: 24px; }}
    .card {{ background: #10192e; border: 1px solid #1e293b; border-radius: 8px; padding: 20px; margin-bottom: 20px; }}
    h1 {{ font-size: 20px; color: #60a5fa; margin-bottom: 8px; }}
    .stats {{ display: flex; gap: 16px; margin-bottom: 20px; }}
    .stat {{ background: #162444; border-radius: 6px; padding: 12px 18px; flex: 1; }}
    .stat-val {{ font-size: 24px; font-weight: bold; color: #38bdf8; }}
    .stat-lbl {{ font-size: 11px; color: #94a3b8; text-transform: uppercase; }}
  </style>
</head>
<body>
  <h1>🚗 V2V RL Training Live Dashboard</h1>
  <p style="color:#64748b;font-size:12px;">Auto-refreshes every 10 seconds | Episode {episode}</p>
  <div class="stats">
    <div class="stat"><div class="stat-lbl">Episodes</div><div class="stat-val">{episode}</div></div>
    <div class="stat"><div class="stat-lbl">Stage</div><div class="stat-val">{curriculum_stage}</div></div>
    <div class="stat"><div class="stat-lbl">Recent Avg Reward</div><div class="stat-val">{avg_10:.1f}</div></div>
    <div class="stat"><div class="stat-lbl">Collision Rate</div><div class="stat-val">{col_rate:.1f}%</div></div>
    <div class="stat"><div class="stat-lbl">Status</div><div class="stat-val" style="color:#4ade80;">{trend}</div></div>
  </div>
  <div class="card">
    <canvas id="rewardChart" height="90"></canvas>
  </div>
  <script>
    new Chart(document.getElementById('rewardChart'), {{
      type: 'line',
      data: {{
        labels: {json.dumps(ep_labels)},
        datasets: [{{
          label: 'Episode Reward',
          data: {json.dumps(sampled_rewards)},
          borderColor: '#38bdf8',
          backgroundColor: 'rgba(56, 189, 248, 0.1)',
          fill: true,
          tension: 0.3
        }}]
      }},
      options: {{
        responsive: true,
        plugins: {{ legend: {{ labels: {{ color: '#94a3b8' }} }} }},
        scales: {{
          x: {{ ticks: {{ color: '#64748b' }}, grid: {{ color: '#1e293b' }} }},
          y: {{ ticks: {{ color: '#64748b' }}, grid: {{ color: '#1e293b' }} }}
        }}
      }}
    }});
  </script>
</body>
</html>""")


async def train(args):
    # Initialize bridge
    bridge = SimulatorBridge(host=args.host, port=args.port)
    await bridge.start_server()

    # Initialize PPO
    trainer = PPOTrainer(
        obs_dim=97,
        act_dim=3,
        device=args.device,
        lr=args.lr,
        gamma=args.gamma,
        gae_lambda=args.gae_lambda,
        clip_eps=args.clip_eps,
        entropy_coef=args.entropy_coef,
        epochs=args.ppo_epochs,
        batch_size=args.batch_size,
    )

    # Load checkpoint if exists
    if args.resume and os.path.exists(args.resume):
        trainer.load(args.resume)

    # Create log directory
    log_dir = Path(args.log_dir)
    log_dir.mkdir(parents=True, exist_ok=True)

    # Training log
    log_file = open(log_dir / 'training_log.jsonl', 'a')

    curriculum_stage = args.curriculum_start
    await bridge.set_curriculum(curriculum_stage)

    # Training statistics
    episode_rewards = []
    episode_lengths = []
    collision_count = 0
    best_avg_reward = -float('inf')

    print(f'\n{"="*60}')
    print(f'  V2V RL Training — PPO')
    print(f'  Episodes: {args.episodes}')
    print(f'  Curriculum start: {curriculum_stage}')
    print(f'  Device: {args.device}')
    print(f'{"="*60}\n')

    for episode in range(1, args.episodes + 1):
        # Reset environment
        seed = episode * 7919 + 42 if args.deterministic else None
        obs = await bridge.reset(seed)

        episode_reward = 0
        episode_steps = 0
        done = False

        while not done:
            # Select action
            action, value = trainer.select_action(obs, deterministic=False)

            # Step environment
            next_obs, reward, terminated, truncated, info = await bridge.step(action)
            done = terminated or truncated

            # Store transition
            trainer.store_transition(obs, action, reward, done, value)

            obs = next_obs
            episode_reward += reward
            episode_steps += 1

            # PPO update when buffer is large enough
            if len(trainer.buffer) >= args.update_interval:
                with torch.no_grad():
                    last_value = trainer.model.get_value(
                        torch.FloatTensor(obs).unsqueeze(0).to(trainer.device)
                    ).item()
                loss = trainer.update(last_value)

        # Episode complete
        episode_rewards.append(episode_reward)
        episode_lengths.append(episode_steps)
        if info.get('collision', False):
            collision_count += 1

        # Logging
        recent_rewards = episode_rewards[-100:]
        avg_reward = np.mean(recent_rewards)
        collision_rate = collision_count / episode

        log_entry = {
            'episode': episode,
            'reward': episode_reward,
            'steps': episode_steps,
            'avg_reward_100': avg_reward,
            'collision': info.get('collision', False),
            'collision_rate': collision_rate,
            'curriculum_stage': curriculum_stage,
            'reason': info.get('reason', ''),
            'timestamp': time.time()
        }
        log_file.write(json.dumps(log_entry) + '\n')
        log_file.flush()

        # Update human-readable TRAINING_SUMMARY.md
        if episode % 5 == 0 or episode <= 10:
            write_summary_report(log_dir, episode, episode_rewards, collision_count, curriculum_stage, best_avg_reward)

        # Print progress
        if episode % args.print_interval == 0:
            print(f'EP {episode:5d} | '
                  f'R={episode_reward:7.1f} | '
                  f'Avg100={avg_reward:7.1f} | '
                  f'Steps={episode_steps:5d} | '
                  f'Col={collision_rate:.2%} | '
                  f'Stage={curriculum_stage}')

        # Save best model
        if avg_reward > best_avg_reward and episode >= 100:
            best_avg_reward = avg_reward
            trainer.save(str(log_dir / 'best_model.pt'))

        # Periodic save
        if episode % args.save_interval == 0:
            trainer.save(str(log_dir / f'model_ep{episode}.pt'))

        # Curriculum advancement
        if episode % 50 == 0 and len(recent_rewards) >= 30:
            cr = sum(1 for e in episode_rewards[-50:] if e < -50) / 50
            if avg_reward > 20 and cr < 0.3 and curriculum_stage < 7:
                curriculum_stage += 1
                await bridge.set_curriculum(curriculum_stage)
                print(f'\n>>> CURRICULUM ADVANCED TO STAGE {curriculum_stage} <<<\n')

    # Final save
    trainer.save(str(log_dir / 'final_model.pt'))
    log_file.close()

    print(f'\n{"="*60}')
    print(f'  Training complete!')
    print(f'  Best avg reward: {best_avg_reward:.1f}')
    print(f'  Final collision rate: {collision_count/args.episodes:.2%}')
    print(f'  Models saved to: {log_dir}')
    print(f'{"="*60}')

    await bridge.close()


def main():
    parser = argparse.ArgumentParser(description='V2V RL Training with PPO')
    parser.add_argument('--episodes', type=int, default=1000)
    parser.add_argument('--curriculum-start', type=int, default=1)
    parser.add_argument('--host', default='localhost')
    parser.add_argument('--port', type=int, default=8765)
    parser.add_argument('--device', default='auto', choices=['auto', 'cpu', 'cuda', 'mps'])
    parser.add_argument('--lr', type=float, default=3e-4)
    parser.add_argument('--gamma', type=float, default=0.99)
    parser.add_argument('--gae-lambda', type=float, default=0.95)
    parser.add_argument('--clip-eps', type=float, default=0.2)
    parser.add_argument('--entropy-coef', type=float, default=0.01)
    parser.add_argument('--ppo-epochs', type=int, default=10)
    parser.add_argument('--batch-size', type=int, default=64)
    parser.add_argument('--update-interval', type=int, default=2048)
    parser.add_argument('--print-interval', type=int, default=10)
    parser.add_argument('--save-interval', type=int, default=100)
    parser.add_argument('--log-dir', default='rl/logs')
    parser.add_argument('--resume', default=None, help='Path to checkpoint to resume from')
    parser.add_argument('--deterministic', action='store_true')
    args = parser.parse_args()

    # Import torch here to get better error message
    try:
        import torch
    except ImportError:
        print('ERROR: PyTorch not found. Install with: pip install torch')
        return

    # Make torch available in the training function
    globals()['torch'] = torch

    # Auto-detect GPU (CUDA / MPS)
    if args.device == 'auto' or args.device == 'cuda':
        if torch.cuda.is_available():
            args.device = 'cuda'
            gpu_name = torch.cuda.get_device_name(0)
            print(f'[GPU] Training on CUDA GPU: {gpu_name}')
        elif hasattr(torch.backends, 'mps') and torch.backends.mps.is_available():
            args.device = 'mps'
            print('[GPU] Training on Apple Silicon MPS')
        else:
            args.device = 'cpu'
            print('[GPU] CUDA/MPS not detected, using CPU')

    asyncio.run(train(args))


if __name__ == '__main__':
    main()
